config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("", login_required(TemplateView.as_view(template_name="pages/home.html")), name="home"),
    path(
        "about/",
        login_required(TemplateView.as_view(template_name="pages/about.html")),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("zeus.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path("api/", include("zeus.api.urls", namespace="api")),
    path("dashboard/", include("zeus.dashboard.urls", namespace="dashboard")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


admin.site.site_header = "Zeus Superuser Panel"
admin.site.site_title = "Zeus Superuser Panel"
admin.site.index_title = "Welcome to Zeus Superuser Panel"

zeus/dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"

urlpatterns = [
    path("overview/", views.overview, name="overview"),
    path("org_options/", views.create_organization, name="create_org"),
    path("org_options/<int:pk>/", views.update_organization, name="update_org"),
    path('org_options/user_management/', views.user_management, name="user_management"),
]

zeus/dashboard/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class Organization(models.Model):
    ORG_name = models.CharField(_("Organization Name"), max_length=100)
    # the owner/ creator of organization
    ORG_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='organization_owned')
    ORG_members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='users', blank=True)
    # ORG_num_of_users = models.PositiveIntegerField()  ==> get the num from members field instead
    ORG_brief = models.TextField(_("Who are we ?"), max_length=250)
    ORG_created = models.DateTimeField(auto_now_add=True)

    ORG_updated = models.DateTimeField(auto_now=True)
    # ORG_event = models.TextField(_("Event"), max_length=300)  ==> make it separated model if t will be used
    # ORG_position =

    def __str__(self):
        return self.ORG_name

    def get_absolute_url(self):
        return reverse('dashboard:update_org', args=[self.pk])

    def add_user(self):
        """staff user add member/s to the organization"""
        pass

    def del_user(self):
        """staff user delete member/s to the organization"""
        pass

zeus/dashboard/forms.py
from django import forms
from .models import Organization


class CreateOrUpdateOrganization(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['ORG_name', 'ORG_brief']

zeus/dashboard/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from .forms import CreateOrUpdateOrganization
from.models import Organization


def overview(request):
    all_orgs = Organization.objects.all()
    context = {'all_orgs': all_orgs}
    return render(request, 'dashboard/overview.html', context)


def org_detail(request, pk):
    org = Organization.objects.get(pk=pk)
    context = {'org': org}
    return render(request, 'dashboard/org_detail.html', context)


@staff_member_required
def create_organization(request):
    if request.method == 'POST':
        create_form = CreateOrUpdateOrganization(data=request.POST)
        if create_form.is_valid():
            cd = create_form.cleaned_data
            new_org = Organization.objects.create(ORG_name=cd['ORG_name'], ORG_owner=request.user, ORG_brief=cd['ORG_brief'])
            new_org.save()
    else:
        create_form = CreateOrUpdateOrganization()

    context = {'create_form': create_form}
    return render(request, 'dashboard/create_organization.html', context)


def update_organization(request, pk):
    if request.method == 'POST':
        org_instance = Organization.objects.get(pk=pk)
        update_form = CreateOrUpdateOrganization(data=request.POST, instance=org_instance)
        if update_form.is_valid():
            update_form.save()
    else:
        org_instance = Organization.objects.get(pk=pk)
        update_form = CreateOrUpdateOrganization(instance=org_instance)

    context = {'update_form': update_form, 'org': org_instance}
    return render(request, 'dashboard/org_detail.html', context)


def user_management(request, pk=None):
    all_orgs = request.user.organization_owned.all()
    context = {'all_orgs': all_orgs}
    return render(request, 'dashboard/user_management.html', context)

zeus/dashboard/templates/dashboard/create_organization.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="col-lg-12">
    <form id="summary-form" action="" method="post" class="form-horizontal" novalidate>
      {% csrf_token %}
      <section class="card">
        <header class="card-header">
          <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
            <!--<a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>-->
          </div>

          <h2 class="card-title">Create Organization</h2>
          <!--<p class="card-subtitle">-->
            <!--Validation summary will display an error list above the form.-->
          <!--</p>-->
        </header>
        <div class="card-body">
          <div class="validation-message">
            <ul></ul>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 control-label text-sm-right pt-2">Full Name <span class="required">*</span></label>
            <div class="col-sm-9">
              <!--<input type="text" name="fullname" class="form-control" title="Please enter a name." placeholder="organization name" required/>-->
              {% render_field create_form.ORG_name class+="form-control" placeholder="Enter organization name" %}
              {{ create_form.ORG_name.errors }}
            </div>
          </div>

          <!--<div class="form-group row">-->
            <!--<label class="col-sm-3 control-label text-sm-right pt-2">Email <span class="required">*</span></label>-->
            <!--<div class="col-sm-9">-->
              <!--<input type="email" name="email" class="form-control" title="Please enter an email address." placeholder="eg.: john@doe.com" required/>-->
            <!--</div>-->
          <!--</div>-->
          <!--<div class="form-group row">-->
            <!--<label class="col-sm-3 control-label text-sm-right pt-2">GitHub</label>-->
            <!--<div class="col-sm-9">-->
              <!--<input type="url" name="url" title="Please enter a valid url." class="form-control" placeholder="eg.: https://github.com/johndoe" />-->
            <!--</div>-->
          <!--</div>-->
          <div class="form-group row">
            <label class="col-sm-3 control-label text-sm-right pt-2">Resume <span class="required">*</span></label>
            <div class="col-sm-9">
              <!--<textarea name="resume" rows="5" title="Your resume is too short." class="form-control" placeholder="Enter your resume" required></textarea>-->
              {% render_field create_form.ORG_brief class+="form-control" placeholder="Enter your resume" %}
              {{ create_form.ORG_brief.errors }}
            </div>
          </div>
        </div>
        <footer class="card-footer">
          <div class="row justify-content-end">
            <div class="col-sm-9">
              <button class="btn btn-primary">Submit</button>
              <!--<button type="reset" class="btn btn-default">Reset</button>-->
            </div>
          </div>
        </footer>
      </section>
    </form>
</div>

  <!--<h1>Create Organization</h1>-->
  <!--<form action="" method="post">-->
    <!--{% csrf_token %}-->
    <!--{{ create_form.as_p }}-->
    <!--<input type="submit" value="create">-->
  <!--</form>-->
{% endblock %}

zeus/dashboard/templates/dashboard/org_detail.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}

  <h4>{{ org.ORG_name }} owned by {{ org.ORG_owner }}</h4> <br> <h4>at {{ org.ORG_created }}</h4> <br>
  {% if org.ORG_members.all %}
    Members:
    {% for member in org.ORG_members.all %}
      <h5><a href="{{ member.get_absolute_url }}">{{ member }}</a></h5>
    {% endfor %}
  {% else %}
    <h5>Members: There is no members yet</h5>
  {% endif %}
  {% if user == org.ORG_owner %}

      <div class="col-lg-12">
          <form id="summary-form" action="" method="post" class="form-horizontal" novalidate>
            {% csrf_token %}
            <section class="card">
              <header class="card-header">
                <div class="card-actions">
                  <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                  <!--<a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>-->
                </div>

                <h2 class="card-title">Update Organization</h2>
                <!--<p class="card-subtitle">-->
                  <!--Validation summary will display an error list above the form.-->
                <!--</p>-->
              </header>
              <div class="card-body">
                <div class="validation-message">
                  <ul></ul>
                </div>
                <div class="form-group row">
                  <label class="col-sm-3 control-label text-sm-right pt-2">Full Name <span class="required">*</span></label>
                  <div class="col-sm-9">
                    <!--<input type="text" name="fullname" class="form-control" title="Please enter a name." placeholder="organization name" required/>-->
                    {% render_field update_form.ORG_name class+="form-control" %}
                    {{ update_form.ORG_name.errors }}
                  </div>
                </div>

                <!--<div class="form-group row">-->
                  <!--<label class="col-sm-3 control-label text-sm-right pt-2">Email <span class="required">*</span></label>-->
                  <!--<div class="col-sm-9">-->
                    <!--<input type="email" name="email" class="form-control" title="Please enter an email address." placeholder="eg.: john@doe.com" required/>-->
                  <!--</div>-->
                <!--</div>-->
                <!--<div class="form-group row">-->
                  <!--<label class="col-sm-3 control-label text-sm-right pt-2">GitHub</label>-->
                  <!--<div class="col-sm-9">-->
                    <!--<input type="url" name="url" title="Please enter a valid url." class="form-control" placeholder="eg.: https://github.com/johndoe" />-->
                  <!--</div>-->
                <!--</div>-->
                <div class="form-group row">
                  <label class="col-sm-3 control-label text-sm-right pt-2">Resume <span class="required">*</span></label>
                  <div class="col-sm-9">
                    <!--<textarea name="resume" rows="5" title="Your resume is too short." class="form-control" placeholder="Enter your resume" required></textarea>-->
                    {% render_field update_form.ORG_brief class+="form-control" %}
                    {{ update_form.ORG_brief.errors }}
                  </div>
                </div>
              </div>
              <footer class="card-footer">
                <div class="row justify-content-end">
                  <div class="col-sm-9">
                    <button class="btn btn-primary">Submit</button>
                    <!--<button type="reset" class="btn btn-default">Reset</button>-->
                  </div>
                </div>
              </footer>
            </section>
          </form>
      </div>



    <!--<h1>Update Organization</h1>-->
    <!--<form action="" method="post">-->
      <!--{% csrf_token %}-->
      <!--{{ update_form.as_p }}-->
      <!--<input type="submit" value="update">-->
    <!--</form>-->
  <!--{% endif %}-->

{% endblock %}

zeus/dashboard/templates/dashboard/overview.html
{% extends 'base.html' %}

{% block content %}
  {% for org in all_orgs %}
    <h4>{{ org.ORG_name }} owned by {{ org.ORG_owner }} at {{ org.ORG_created }}</h4> <br>
    <p><a href="{{ org.get_absolute_url }}"><button class="btn btn-primary">org detail</button></a></p>
  {% endfor %}


  {% if user.is_staff %}
    <a href="{% url 'dashboard:create_org' %}"><button class="btn btn-primary">Create Org</button></a>

  {% endif %}
{% endblock %}

zeus/dashboard/templates/dashboard/user_management.html
{% extends 'base.html' %}

{% block content %}
  {% for org in all_orgs %}
    <h4>{{ org.ORG_name }} owned by {{ org.ORG_owner }}</h4> <br> <h4>at {{ org.ORG_created }}</h4> <br>
    {% if org.ORG_members.all %}
      <h5>Members:</h5>
      {% for member in org.ORG_members.all %}
        <h5><a href="{{ member.get_absolute_url }}">{{ member }}</a></h5>
      {% endfor %}
    {% else %}
      <h5>Members: There is no members yet</h5>
    {% endif %}
    <p><a href="{{ org.get_absolute_url }}"><button class="btn btn-primary">org detail</button></a></p>
  {% endfor %}


{% endblock %}